#!/usr/bin/env python3
"""gl1 icon atlas — ICON_ORDER / aliases matching src/icons.zig IconId."""
from __future__ import annotations

# Default order matches src/icons.zig IconId.
ICON_ORDER = [
    "cursor_arrow",
    "cursor_hand_open",
    "cursor_hand_closed",
    "cursor_text",
    "cursor_cross",
    "cursor_resize_h",
    "cursor_resize_v",
    "cursor_resize_nwse",
    "cursor_resize_nesw",
    "cursor_busy",
    "arrow_down",
    "arrow_up",
    "arrow_left",
    "arrow_right",
    "tree_leaf",
    "folder",
    "folder_open",
    "check",
    "close",
    "plus",
    "minus",
    "search",
    "settings",
    "home",
    "save",
    "copy",
    "paste",
    "trash",
    "eye",
    "lock",
    "star",
    "download",
    "emoji_smile",
    "emoji_heart",
    "emoji_laugh",
    "emoji_thumbs_up",
    "emoji_fire",
    "emoji_party",
    "emoji_cry",
    "emoji_think",
    "emoji_clap",
    "emoji_100",
    "arrow_s",
    "arrow_n",
    "arrow_w",
    "arrow_e",
    "long_arrow_w",
    "long_arrow_e",
    "chevron_s",
    "chevron_n",
    "chevron_s_dark",
    "chevron_n_dark",
]

PRIMARY_ALIAS = {
    "cursor_arrow": "pointer",
    "cursor_hand_open": "hand",
    "cursor_hand_closed": "grab",
    "cursor_text": "ibeam",
    "cursor_cross": "crosshair",
    "cursor_resize_h": "resize-ew",
    "cursor_resize_v": "resize-ns",
    "cursor_resize_nwse": "resize-nwse",
    "cursor_resize_nesw": "resize-nesw",
    "cursor_busy": "wait",
    "arrow_down": "caret-down",
    "arrow_up": "caret-up",
    "arrow_left": "caret-left",
    "arrow_right": "caret-right",
    "tree_leaf": "leaf",
    "folder": "dir",
    "folder_open": "dir-open",
    "check": "ok",
    "close": "x",
    "plus": "plus",
    "minus": "minus",
    "search": "find",
    "settings": "gear",
    "home": "home",
    "save": "disk",
    "copy": "copy",
    "paste": "paste",
    "trash": "delete",
    "eye": "eye",
    "lock": "lock",
    "star": "star",
    "download": "download",
    "emoji_smile": "smile",
    "emoji_heart": "heart",
    "emoji_laugh": "joy",
    "emoji_thumbs_up": "thumbs-up",
    "emoji_fire": "fire",
    "emoji_party": "tada",
    "emoji_cry": "sad",
    "emoji_think": "thinking",
    "emoji_clap": "clap",
    "emoji_100": "hundred",
    "arrow_s": "arrow-s",
    "arrow_n": "arrow-n",
    "arrow_w": "arrow-w",
    "arrow_e": "arrow-e",
    "long_arrow_w": "long-arrow-w",
    "long_arrow_e": "long-arrow-e",
    "chevron_s": "chevron-s",
    "chevron_n": "chevron-n",
    "chevron_s_dark": "chevron-s-dark",
    "chevron_n_dark": "chevron-n-dark",
}

EXTRA_ALIASES = {
    "cursor_arrow": ["default", "cursor"],
    "cursor_hand_open": ["hand_open", "hand-open"],
    "cursor_hand_closed": ["hand_closed", "hand-closed", "grip", "grabbing"],
    "cursor_text": ["text"],
    "cursor_resize_h": ["resize_ew"],
    "cursor_resize_v": ["resize_ns"],
    "cursor_resize_nwse": ["resize_nwse"],
    "cursor_resize_nesw": ["resize_nesw"],
    "arrow_down": ["v", "tree-open", "tree_open", "chevron-down"],
    "arrow_up": ["^", "chevron-up"],
    "arrow_left": ["<", "chevron-left"],
    "arrow_right": [">", "tree-closed", "tree_closed", "chevron-right"],
    "folder_open": ["dir_open"],
    "check": ["tick"],
    "close": ["cancel"],
    "plus": ["add"],
    "minus": ["subtract", "remove"],
    "search": ["filter"],
    "settings": ["cog"],
    "eye": ["visible"],
    "emoji_thumbs_up": ["thumbsup"],
}


def main():
    print(f"ICON_ORDER: {len(ICON_ORDER)} ids (use tools/pack_icons_from_original.py)")


if __name__ == "__main__":
    main()
